### ISSUE TITLE
UI Feedback

### ISSUE THREAD

**Issue by subramanian-elavathur** [Abiey2579/keeps-goal#1]
# Header alignment

Lets align the header to the top

![Screenshot 2022-12-08 at 5 59 52 PM](https://user-images.githubusercontent.com/4240966/206446648-1163d69f-7bee-4b97-98f1-206aec137c20.png)

as per the design
<img width="694" alt="Screenshot 2022-12-08 at 6 00 32 PM" src="https://user-images.githubusercontent.com/4240966/206446751-55e89f1c-a97d-410a-bbbf-8d3dc4d5a75e.png">

# Habit item alignments

Can we align the goal name in center?

![Screenshot 2022-12-08 at 6 04 25 PM](https://user-images.githubusercontent.com/4240966/206447389-07c8d4e5-4423-4989-bbd3-d78b737e7d4c.png)

**Comment by Abiey2579** [comment]
# Fixing Issue #1 - UI Feedback

I have centered the `Top Navigation elements Perfectly`. I have used ruler to Make sure all elements are centered to the middle.
`Commit` https://github.com/Abiey2579/keeps-goal/commit/c57351d2e388697d140e8dfec91cd04331adf17a

![UI FIXED - ALIGN TOP NAVIGATION](https://user-images.githubusercontent.com/53899426/206571861-481eb6de-15e2-4614-aefe-03b8e23917ae.jpg)

**Comment by Abiey2579** [comment]
# Fixed Issue #1 - Habit Item Alignments

Issue was fixed by add `height of 100%` on the table data `<td>` that holds Habit Name and Habit Type in `OnprogressGoals.tsx` and `GoalsDone.tsx`.

`Commit` https://github.com/Abiey2579/keeps-goal/commit/feed94ee39c8b35698e10c8180793716e3d5ba7a

**Comment by Abiey2579** [comment]
# ISSUE WAS FIXED
