### ISSUE TITLE
Extract out Goal Component

### ISSUE THREAD

**Issue by subramanian-elavathur** [Abiey2579/keeps-goal#2]
Please extract out the highlighted section below into a new react component. 

`GoalList.tsx - Line 105`

![Screenshot 2022-12-08 at 6 32 29 PM](https://user-images.githubusercontent.com/4240966/206453391-24e3b3fd-6a7e-4e5a-aebf-a5a1e00ab7a8.png)

**Comment by Abiey2579** [comment]
# Issue Fixed

I have extracted the `Goal Component`.

I have placed below code in a file called `OnprogressGoals.tsx`.

![OnprogressGoals](https://user-images.githubusercontent.com/53899426/206504305-37d304c4-6fa3-4f31-be6a-f0c416b754d8.jpg)

And also I have placed below in a file called `GoalsDone.tsx`.

![GoalsDone](https://user-images.githubusercontent.com/53899426/206504983-eb084185-b326-41c1-84b5-557ed9f59e14.jpg)


`Commit Link` https://github.com/Abiey2579/keeps-goal/commit/88b636823f1e2de22551f89674927573041e6271
